name: MoustacheBrewingCo
favicon: null
layout_spectrum: 0.3872087097261101
typography_spectrum: 0.5597945395857096
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.01088762516155839
  lightness: 0.3117037091869861
  saturation: 0.7968538240529597
  rhythmicContrast: 0.19176279776729643
purpose: []
